# -*- coding: utf-8 -*-
"""Semester_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Q6Z4PBaKNZ4ZvG4C-V_44s4Hg8RSNak
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import calendar


df = pd.read_csv("ERA5_Land_Daily_Temp_2000_2025 (1).csv")


df['date'] = pd.to_datetime(df['date'])


df['year'] = df['date'].dt.year

comfortable = df[(df['temp_c'] >= 18) & (df['temp_c'] <= 25)]

yearly_comfort = (
    comfortable
    .groupby('year')
    .size()
    .reset_index(name='comfortable_days')
)


fig = px.bar(
    yearly_comfort,
    x='year',
    y='comfortable_days',
    title='Yearly Comfortable Temperature Days in Islamabad (2000–2025)',
    labels={
        'year': 'Year',
        'comfortable_days': 'Number of Comfortable Days'
    }
)

fig.update_layout(
    template='plotly_white',
    title_font_size=20,
    xaxis_tickangle=-45,
    bargap=0.2
)

fig.show()


fig = px.line(
    yearly_comfort,
    x='year',
    y='comfortable_days',
    markers=True,
    title='Trend of Comfortable Temperature Days in Islamabad'
)

fig.update_layout(
    template='plotly_white',
    title_font_size=20
)

fig.show()


df['month'] = df['date'].dt.month

comfortable = df[
    (df['temp_c'] >= 18) & (df['temp_c'] <= 25)
]

monthly_comfort = (
    comfortable
    .groupby(['year', 'month'])
    .size()
    .reset_index(name='count')
)


heatmap_data = monthly_comfort.pivot(
    index='year',
    columns='month',
    values='count'
).fillna(0)

fig = px.imshow(
    heatmap_data,
    aspect='auto',
    title='Monthly Distribution of Comfortable Temperature Days in Islamabad',
    labels=dict(
        x='Month',
        y='Year',
        color='Comfortable Temperature Days'
    )
)

fig.update_layout(template='plotly_white')
fig.show()

from google.colab import drive
drive.mount('/content/drive')

comfortable = df.loc[
    (df['temp_c'] >= 18) & (df['temp_c'] <= 25)
].copy()



yearly_total = (
    comfortable
    .groupby('year')
    .size()
    .reset_index(name='total_comfortable_days')
)
monthly_counts = (
    comfortable
    .groupby(['year', 'month'])
    .size()
    .reset_index(name='monthly_days')
)

# For each year, get month with maximum comfortable days
idx = monthly_counts.groupby('year')['monthly_days'].idxmax()
top_months = monthly_counts.loc[idx].reset_index(drop=True)

import calendar

top_months['month_name'] = top_months['month'].apply(
    lambda x: calendar.month_name[x]
)

summary_table = yearly_total.merge(
    top_months[['year', 'month_name', 'monthly_days']],
    on='year'
)

summary_table.rename(columns={
    'month_name': 'Top Comfortable Month',
    'monthly_days': 'Comfortable Days in Top Month'
}, inplace=True)


import plotly.graph_objects as go

fig = go.Figure(data=[go.Table(
    header=dict(
        values=[
            "<b>Year</b>",
            "<b>Total Comfortable Days</b>",
            "<b>Top Comfortable Month</b>",
            "<b>Days in Top Month</b>"
        ],
        fill_color='#1f2937',   # dark modern header
        font=dict(color='white', size=14),
        align='center'
    ),
    cells=dict(
        values=[
            summary_table['year'],
            summary_table['total_comfortable_days'],
            summary_table['Top Comfortable Month'],
            summary_table['Comfortable Days in Top Month']
        ],
        fill_color='#f9fafb',
        font=dict(color='#111827', size=13),
        align='center',
        height=28
    )
)])

fig.update_layout(
    title=dict(
        text="Yearly Summary of Comfortable Temperature Days in Islamabad (2000–2025)",
        x=0.5,
        font=dict(size=20)
    ),
    margin=dict(l=20, r=20, t=60, b=20)
)

fig.show()



# Add coordinates for Islamabad (approx.)
df['lat'] = 33.6844
df['lon'] = 73.0479


# Total comfortable days per year
comfortable = df[(df['temp_c'] >= 18) & (df['temp_c'] <= 25)].copy()

yearly_comfort_map = (
    comfortable.groupby('year')
    .agg({'lat':'first', 'lon':'first', 'temp_c':'count'})  # temp_c column now stores number of comfortable days
    .reset_index()
)

yearly_comfort_map.rename(columns={'temp_c':'comfortable_days'}, inplace=True)


import plotly.express as px

px.set_mapbox_access_token("YOUR_MAPBOX_ACCESS_TOKEN")  # sign up for free at mapbox.com

fig = px.scatter_mapbox(
    yearly_comfort_map,
    lat="lat",
    lon="lon",
    size="comfortable_days",  # bubble size based on comfortable days
    color="comfortable_days", # color scale
    hover_name="year",
    hover_data={"lat":False, "lon":False, "comfortable_days":True},
    color_continuous_scale="Viridis",
    size_max=30,
    zoom=6,
    title="Islamabad: Comfortable  Temperature Days Per Year (Interactive Map)"
)

fig.update_layout(
    mapbox_style="carto-positron",  # modern, clean map style
    margin={"r":0,"t":50,"l":0,"b":0}
)

fig.show()


fig = px.scatter_mapbox(
    yearly_comfort_map,
    lat="lat",
    lon="lon",
    size="comfortable_days",
    color="comfortable_days",
    hover_name="year",
    animation_frame="year",  # slider
    color_continuous_scale="Viridis",
    size_max=30,
    zoom=6,
    mapbox_style="carto-positron",
    title="Interactive Yearly Map of Comfortable Temperature Days"
)
fig.show()
